# Generated by Django 5.2.4 on 2025-07-11 08:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionType',
            fields=[
                ('name', models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('NEUTRAL', 'Neutral'), ('ANGRY', 'Angry'), ('EXCITED', 'Excited'), ('ANXIOUS', 'Anxious')], max_length=50, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emoticon', models.CharField(max_length=20)),
                ('degree', models.IntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Emotion Type',
                'verbose_name_plural': 'Emotion Types',
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('employee', 'Employé'), ('manager', 'Manager'), ('director', 'Directeur'), ('pole_directeur', 'Directeur de Pôle')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, help_text='Manager du collaborateur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emotion_degree', models.IntegerField(editable=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('week_number', models.PositiveIntegerField(editable=False)),
                ('month', models.PositiveIntegerField(editable=False)),
                ('year', models.PositiveIntegerField(editable=False)),
                ('half_day', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], editable=False, max_length=10)),
                ('date_period', models.CharField(editable=False, max_length=20)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to=settings.AUTH_USER_MODEL)),
                ('emotion_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='emotionalTracker.emotiontype')),
            ],
            options={
                'verbose_name': 'Emotion',
                'verbose_name_plural': 'Emotions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='emotionalTracker.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='emotionalTracker.entity')),
            ],
            options={
                'unique_together': {('name', 'entity')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='emotionalTracker.department')),
            ],
            options={
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.AddField(
            model_name='collaborator',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='emotionalTracker.service'),
        ),
    ]
