# Generated by Django 5.2.4 on 2025-07-14 07:37

import emotionalTracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionalTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='date',
            field=models.DateTimeField(default=emotionalTracker.models.default_date_plus_3h),
        ),
    ]
