# Generated by Django 5.2.4 on 2025-07-14 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionalTracker', '0002_alter_emotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='emotionalTracker.service'),
        ),
    ]
