# Generated by Django 5.2.4 on 2025-07-14 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionalTracker', '0003_alter_collaborator_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='emotionalTracker.service'),
        ),
    ]
