# Generated by Django 5.2.4 on 2025-07-14 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionalTracker', '0004_alter_collaborator_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='role',
            field=models.CharField(choices=[('employee', 'Employé'), ('manager', 'Manager'), ('director', 'Directeur'), ('pole_directeur', 'Directeur de Pôle'), ('admin', 'Administrateur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='emotionalTracker.department'),
        ),
    ]
