# Generated by Django 5.2.4 on 2025-07-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionalTracker', '0005_alter_collaborator_role_alter_service_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborators', to='emotionalTracker.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='emotionalTracker.department'),
        ),
    ]
