# Generated by Django 5.2.4 on 2025-07-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotionalTracker', '0006_alter_collaborator_service_alter_service_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion',
            old_name='date_period',
            new_name='_date_period',
        ),
    ]
