# Generated by Django 5.2.4 on 2025-07-15 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionalTracker', '0007_rename_date_period_emotion__date_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='emotionalTracker.entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='emotionalTracker.cluster'),
        ),
    ]
