# Generated by Django 5.2.4 on 2025-07-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionalTracker', '0008_alter_department_entity_alter_entity_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='role',
            field=models.CharField(choices=[('employee', 'Employé'), ('manager', 'Manager'), ('department_director', 'Directeur / Chef de département'), ('entity_director', "Directeur d' entité"), ('pole_director', 'Directeur de Pôle'), ('admin', 'Administrateur')], max_length=20),
        ),
    ]
