# Generated by Django 5.2.4 on 2025-07-15 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionalTracker', '0009_alter_collaborator_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emotionalTracker.cluster'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emotionalTracker.department'),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emotionalTracker.entity'),
        ),
    ]
